### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by myungjoo** [RidgeRun/gst-shark#105]
Although gst-shark has declared its license as LGPL-2.1 with https://github.com/RidgeRun/gst-shark/blob/master/COPYING , license tools complain a lot about its licensing risks.

For example:
```
Finding #1 
Priority: Very High 

This file is under a commercial / proprietary license from RidgeRun which is not an open source license. This file, and any other code it refers to that is under the RidgeRun license, should be removed from the repo. 

/eclipse/GstSharkFeature/feature.xml
/eclipse/GstSharkFeature/features/GstSharkFeature_1.0.0.201604062022.jar/feature.xml
/eclipse/GstSharkFeature/features/GstSharkFeature_1.0.0.201604062027.jar/feature.xml
/eclipse/GstSharkFeature/features/GstSharkFeature_1.0.0.201604070929.jar/feature.xml
/eclipse/GstSharkFeature/features/GstSharkFeature_1.0.0.201604070930.jar/feature.xml
/eclipse/GstSharkSite/features/GstSharkFeature_1.0.0.201604070936.jar/feature.xml
/eclipse/GstSharkFeature/content.jar/content.xml
/eclipse/GstSharkSite/content.jar/content.xml
```

and, the file https://github.com/nnstreamer/nnshark/blob/master/eclipse/GstSharkFeature/feature.xml actually contradicts with LGPL.

Could you please clarify the license of the contradicting files?

**Comment by AleSoHe** [comment]
Hi @myungjoo 
Thanks for the finding. Previous versions of GstShark were using this proprietary on purpose, but it was not needed anymore when we moved to LGPL-2.

The eclipse plugin was removed in the latest version (**v0.7.5**), so you won't find RidgeRun's license anymore.

**Comment by michaelgruner** [comment]
Thanks @AleSoHe . Closing the issue, @myungjoo please feel free to reopen if needed.
