### ISSUE TITLE
Segmentation fault (core dumped) with proctime tracer

### ISSUE THREAD

**Issue by bebbajr** [RidgeRun/gst-shark#119]
### When I try to use the "proctime" tracer i get an segementation fault. Can anybody help me?

I get the same output on my Ubuntu 20.04 virtual machine aswell as on my Raspberry Pi Compute Module 4 running with Debian 10 (Buster).
I don't get this fault, when I'm using another Gst-Shark tracer like "cpuusage" or "bitrate".

----------------------------------------------------------------------------------------------------------------------------------------------------

This is the command i executed:

GST_DEBUG="GST_TRACER:7" GST_TRACERS="proctime" gst-launch-1.0 -v ximagesrc ! video/x-raw,framerate=20/1 ! videoscale ! videoconvert ! x264enc tune=zerolatency bitrate=500 speed-preset=superfast ! rtph264pay ! udpsink host=127.0.0.1 port=5000

----------------------------------------------------------------------------------------------------------------------------------------------------

This is the related console output:

:00:00.012326302 22597 0x559c7bfe04a0 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x559c7be2fd80 (cpuusage)
0:00:00.012360466 22597 0x559c7bfe04a0 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x559c7be2fe40 (graphic)
0:00:00.012368211 22597 0x559c7bfe04a0 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x559c7be2ff00 (proctime)
0:00:00.012374939 22597 0x559c7bfe04a0 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x559c7bfec840 (interlatency)
0:00:00.012381557 22597 0x559c7bfe04a0 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x559c7bfec900 (scheduletime)
0:00:00.012406127 22597 0x559c7bfe04a0 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x559c7bfec9c0 (framerate)
0:00:00.012412093 22597 0x559c7bfe04a0 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x559c7bfeca80 (queuelevel)
0:00:00.012418456 22597 0x559c7bfe04a0 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x559c7bfecb40 (bitrate)
0:00:00.012423936 22597 0x559c7bfe04a0 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x559c7bfecc00 (buffer)
0:00:00.012460614 22597 0x559c7bfe04a0 TRACE             GST_TRACER gsttracerrecord.c:111:gst_tracer_record_build_format: proctime.class, element=(structure)"scope\,\ type\=\(type\)gchararray\,\ related-to\=\(GstTracerValueScope\)GST_TRACER_VALUE_SCOPE_ELEMENT\;", time=(structure)"scope\,\ type\=\(type\)gchararray\,\ related-to\=\(GstTracerValueScope\)GST_TRACER_VALUE_SCOPE_PROCESS\;";
0:00:00.012474358 22597 0x559c7bfe04a0 DEBUG             GST_TRACER gsttracerrecord.c:125:gst_tracer_record_build_format: new format string: proctime, element=(string)%s, time=(string)%s;
Segmentation fault (core dumped)

**Comment by michaelgruner** [comment]
Hi all. Thanks for the reports and sorry for the slow response. I've published a new release with a fix for this. Please feel free to reopen if it persists.
