### ISSUE TITLE
interlatency: should not include sink synchronization pause

### ISSUE THREAD

**Issue by gdesmott** [RidgeRun/gst-shark#16]
The interlatency as a fork of the upstream 'latency' tracer suffers the same bug as the upstream one did: https://bugzilla.gnome.org/show_bug.cgi?id=788431

The fix should be pretty similar to the upstream one: https://cgit.freedesktop.org/gstreamer/gstreamer/commit/?id=41e35c334b8d53328d73fba4dc7fd433021fff4c

**Comment by josejich** [comment]
Very interesting, thanks for the heads up!. I will check this out.

**Comment by rrcarlosrodriguez** [comment]
@gdesmott thanks for the hint! It was fixed with commit eae416a090d68f61eff28cbb87f54284cec45196
