### ISSUE TITLE
compilation depends on gstreamer being compiled with --enable-gst-debug

### ISSUE THREAD

**Issue by cpackham** [RidgeRun/gst-shark#51]
Hi,

I've recently added gst-shark as a package in [buildroot](https://buildroot.org/). As buildroot is primarily for embedded systems it tends to default to producing the smallest binaries. As such gstreamer is configured with --disable-gst-debug unless debug support is explicitly enabled. gstgraphic.c seems to depend on gstreamer being compiled with debug support. This all leads to the following [build errors](http://autobuild.buildroot.net/results/09b894b0775df2dd87d8fb2d53c6a243d8668aba/build-end.log)
```
gstgraphic.c: In function 'log_graphic':
gstgraphic.c:59:3: error: attempt to use poisoned "gst_debug_log_valist"
   gst_debug_log_valist (cat, GST_LEVEL_TRACE, "", "", 0, NULL, fmt, var_args);
   ^
gstgraphic.c: In function 'do_element_change_state_post':
gstgraphic.c:75:18: error: 'GST_CAT_STATES' undeclared (first use in this function); did you mean 'GST_TASK_STATE'?
     log_graphic (GST_CAT_STATES,
                  ^~~~~~~~~~~~~~
                  GST_TASK_STATE
gstgraphic.c:75:18: note: each undeclared identifier is reported only once for each function it appears in
``` 

If this is intended then I can fix the buildroot package to select the appropriate option for gstreamer when gst-shark is enabled. I thought I'd bring it up here just in case there is a simple change that can be made to gst-shark.

**Comment by michaelgruner** [comment]
Thanks for reporting this back to us. My first thought was that it didn’t make sense to build GstShark if debug was disabled, but on the other hand it writes the CTF trace which is completely independent from the debugging subsystem. So I think one should be able to build and use it without debug support.

I also don’t think it’s worth to force the user to rebuild GStreamer with debug just for that single line. I think that’s something we should fix on our side. I may be able to look into this tomorrow.

**Comment by michaelgruner** [comment]
I was done with the fixes for when GStreamer was built without debug support, when I realized tracers get disabled when debug is disabled. Take a look at [gst.c:L812](https://github.com/GStreamer/gstreamer/blob/master/gst/gst.c#L812):

```c
#ifndef GST_DISABLE_GST_DEBUG
  _priv_gst_tracing_init ();
#endif
```

Given this, it only makes sense to build gst-shark if Gstreamer was built with debugging support. I added a check to the configure script in order to fail out if debugging is disabled. Master is already updated.

**Comment by cpackham** [comment]
Makes sense. FYI the buildroot fix for this is https://git.buildroot.net/buildroot/commit/?id=e9d8a31100f08cb591ded583288b20d07769bcba.
