### ISSUE TITLE
Using gst-shark in custom gstreamer application

### ISSUE THREAD

**Issue by Giangblackk** [RidgeRun/gst-shark#59]
I'm trying to use gst-shark in a custom gstreamer application instead of using `gst-launch-1.0` application.
I cannot find any resource of how to do it.
When I use `gst-inspect-1.0` to inspect elements like `cpuusgae`, the only thing shown is an description, without any pad capacity or properties.
Is there any example or tutorial of how to use gst-shark in custom gstreamer-application?
Thanks

**Comment by michaelgruner** [comment]
Hi @Giangblackk gst-shark is a set of tracers, not elements. As such, `cpuusage`, `bitrate`, and all the other traces will not expose pads nor properties.

Here are some examples on how to use the tracers:
https://developer.ridgerun.com/wiki/index.php?title=GstShark_Examples

**Comment by Giangblackk** [comment]
@michaelgruner thanks for your explanation.

I followed the GstShark example, and found out that GstShark doesn't work with simple gstreamer application that doesn't have some kind of main loop.
I can make GstShark work by adding `GMainLoop` or `gtk_main` to  the gstreamer applications.
I close the issue.

**Comment by garygumdrops** [comment]
Are there any notes about how to use the tracers from within an application (not gst-launch)?
I have used **export** to set up the environment variables as per the examples, but I don't see any dot files or other files anywhere, but I do if I run gst-launch-1.0 with no other special commands (it just uses the environment variables in the shell).

My application is running on an ARM target with Linux and the pipeline created is within a shared library. I didn't have a GMainLoop as didn't need one but I tried adding one just in case as [Giangblackk](https://github.com/Giangblackk) commented that GstShark seems to need a main loop of some kind. Do I have to pre-load gstsharktracers.so or some other hidden magic that happens when using gst-launch-1.0?

**Comment by michaelgruner** [comment]
You shouldn't need anything besides the initial `gst_init` and the `GMainLoop`. Is it possible for you to share your app, or a distilled version of it?

**Comment by garygumdrops** [comment]
I could paste chunks of the code here but I haven't added anything specific to the code for gst-shark and the pipeline is working just fine.
I did check my app (same source) on my Linux host machine and I do see the TRACE debug in the log, so maybe there is something wrong with the build I have for the imx6. I had also tried adding 'perf' into my pipeline just before the appsink and I don't see anything being dumped for that either. I have definitely used the same export commands on the host and target (well paths different). Here's a couple of variations:

export GST_DEBUG="*PERF*:4"
export GST_DEBUG_DUMP_DOT_DIR="/home/root"
export GST_SHARK_LOCATION="/home/root"
export GST_TRACERS="cpuusage"

declare -x GST_DEBUG="GST_TRACER:7"
declare -x GST_TRACERS="proctime"

If I run the following command on the target:

gst-launch-1.0 -v imxv4l2videosrc device=/dev/video0 ! imxvpuenc_h264 bitrate=10000 ! perf print-arm-load=true ! filesink location=/tmp/file.mp4

I see output from perf but nothing else (no TRACE). I do see some .dot files though.

If I add perf to my pipeline in the code running on the target then I don't see any perf output or any .dot files.

I didn't personally build gst-shark for the target as it was done by my boss when he built me the yocto distribution. The libs are there but maybe he didn't build it properly or missed something else out that was needed.

**Comment by michaelgruner** [comment]
If I recall correctly, most Yocto builds compile out the tracing support in GStreamer. Can you add the following to your `local.conf`:

```
IMAGE_INSTALL_append = "gst-tracers"
```

**Comment by garygumdrops** [comment]
Yes that was useful thanks Michael. I found the notes from [this page](https://developer.ridgerun.com/wiki/index.php?title=GstShark_-_Getting_Started#Dependencies) as well but I think my boss found it on his own.

I have noticed some TRACE log entries now so when I get a free moment, I'll come back to this again and do some profiling.
