### ISSUE TITLE
how to understand the interlantecy plot

### ISSUE THREAD

**Issue by weizhou1001** [RidgeRun/gst-shark#86]
Hi, I was trying to use Gst-Shark to understand the latency for each plugin, but got bit confused by the plot.

I ran the command: 
`GST_DEBUG="GST_TRACER:7" GST_TRACERS="interlatency" gst-launch-1.0 v4l2src device=/dev/video0 io-mode=2 ! 'image/jpeg,width=1280,height=720,framerate=60/1' ! videorate ! 'image/jpeg,framerate=12/1' ! nvjpegdec ! 'video/x-raw' ! nvvidconv ! 'video/x-raw(memory:NVMM),width=320,height=240' ! omxh264enc insert-sps-pps=true ! h264parse ! rtph264pay pt=96 ! udpsink host=127.0.0.1 port=8001 sync=false -e`
This is taking the sensor device, restrict framerate to 12, convert to nvidia memory resize to 320x240. then encode it for UDP sink.

I got the picture like this 
![image](https://user-images.githubusercontent.com/48662491/91672831-0de3fb80-eb74-11ea-892c-1debcbfd613b.png)

So to get the latency for the entire pipeline, do I sum all the plugins at one time? Some colours are too close, i can't really tell which is which. But should I sum capsfilter0_src, videorate0_src, ... etc. to get the entire latency?  

Thanks!

**Comment by michaelgruner** [comment]
The interlatency tracer will report latency between the source element and the given element, inclusive. For example, using your pipeline as an example, the `nvjpeg0_src` graph shows the latency between `v4l2src0:src` pad to the `nvjpeg0:src` pad. As you can see, this includes the intermediate elements:
```
v4l2src ! capsfilter0 ! videorate ! capsfilter1 ! nvjpegdec ! capsfilter2 ! nvvidconv !  ... ! udpsink
        ^-----------------------. .------------------------^
                                 V
                          nvjpeg_0 plot
```

If you would like to have the latency introduced by a single element, say the `nvjpegdec`, you would need to subtract the value from the `nvjpegdec0_src` from the `capsfilter1_src`.
```
nvjpegdec_latency[t] =  nvjpegdec0_src[t] - capsfilter1_src[t]
```

Having said that, please recall that this tracer will **only** measure the latency **in** the pipeline. It will not measure the latency of the network nor the receiving client. Similarly, it cannot measure latency introduced by the capture hardware.

**Comment by weizhou1001** [comment]
Thanks for the information!
