### ISSUE TITLE
Segfault in read-only area

### ISSUE THREAD

**Issue by michaelgruner** [RidgeRun/gst-shark#9]
If I run a pipeline in a read-only location I get a segmentation fault

`G_DEBUG=fatal-warnings GST_DEBUG=GST_TRACE:9 GST_TRACERS=framerate  gst-ins
ect-1.0 --gst-disable-segtrap --gst-disable-registry-fork --gst-debug=2
0:00:00.107046890  2310     0x32408380 ERROR  st-inspect-1.0[2310]: unhandled level 2 translation fault (11) at 0x00000000, esr 0
x92000006
[00m              default gstctf.c:520:create_ctf_path:gd = ffffffc0405bb000
[00m Directory gstshark_2017-04-12_01:38:56 could not be created[  804.425238] [00000000] *pgd=00000000405fb003.
0:00:00.107170090  2310     0x32408380 ERR, *pud=00000000405fb003OR                default gstctf.c:548:ctf_file_ini, *pmd=000000
0000000000t: Could not open datastream file, path does not exist.
0:
00:00.107202420  2310     0x32408380 ERROR  
              default gstctf.c:553:ctf_file_init: PU: 1 PID: 2310 Comm: gst-inspect-1.0 Not tainted 4.6.0-243800-g10a4810-dirty #
1
0m Could not open metadata file, path does not exist.
[  804.476792] Hardware name: ZynqMP ZCU106 RevA (DT)
[  804.486346] task: ffffffc87b18e600 ti: ffffffc0405f4000 task.ti: ffffffc0405f4000
[  804.493809] PC is at 0x7fa71baad8
[  804.497105] LR is at 0x7fa60eab78
[  804.500404] pc : [<0000007fa71baad8>] lr : [<0000007fa60eab78>] pstate: 60000000
[  804.507782] sp : 0000007fefe8c8d0
[  804.511079] x29: 0000007fefe8c8d0 x28: 0000000000419728 
[  804.516368] x27: 0000007fa7504000 x26: 0000000000000000 
[  804.521662] x25: 0000007fa7504e69 x24: 0000000000000008 
[  804.526957] x23: 000000000000065a x22: 000000003241b005 
[  804.532252] x21: 00000000323f3930 x20: 0000007fa7504e61 
[  804.537547] x19: 0000007fa6117c88 x18: 0000000000000000 
[  804.542842] x17: 0000007fa71baab8 x16: 0000007fa60fe4c8 
[  804.548137] x15: 003b9aca00000000 x14: 650a0a3b7d0a3b74 
[  804.553431] x13: 7865746e6f635f74 x12: 656b636170207463 
[  804.558726] x11: 75727473203d3a20 x10: 747865746e6f632e 
[  804.564021] x9 : 74656b6361702020 x8 : 0a3b7d0a3b30203d 
[  804.569316] x7 : 2064695f6d616572 x6 : 000000003241b65f 
[  804.574611] x5 : 0000000000400000 x4 : 0000000000000003 
[  804.579905] x3 : 0000000000000000 x2 : 000000000000065a 
[  804.585200] x1 : 0000000000000001 x0 : 000000003241b005 
[  804.590494] 
Segmentation fault`

**Comment by rrcarlosrodriguez** [comment]
Fixed with 64ca36ffc211d09059dec872ddab74de75af8a24
